<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX8u9ho5\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX8u9ho5/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX8u9ho5.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX8u9ho5\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerX8u9ho5\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'X8u9ho5',
    'container.build_id' => '12ccb7fe',
    'container.build_time' => 1616098638,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX8u9ho5');
